# Deployment for Book Catalog Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: library
  labels:
    app: library
spec:
  replicas: 3
  selector:
    matchLabels:
      app: library
  template:
    metadata:
      labels:
        app: library
    spec:
      containers:
      - name: library
        image: s224078886.azurecr.io/library:1
        imagePullPolicy: Always 
        ports:
        - containerPort: 8001
      imagePullSecrets:
      - name: acr-secret

---
# Service for Book Catalog
apiVersion: v1
kind: Service
metadata:
  name: library-service-book
spec:
  selector:
    app: library
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
  type: LoadBalancer

---
# Deployment for Inventory Management Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
  labels:
    app: inventory
spec:
  replicas: 3
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
      - name: inventory
        image: s224078886.azurecr.io/inventory:1
        imagePullPolicy: Always 
        ports:
        - containerPort: 8002
      imagePullSecrets:
      - name: acr-secret

---
# Service for Inventory Management
apiVersion: v1
kind: Service
metadata:
  name: inventory-service-management
spec:
  selector:
    app: inventory
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8002
  type: LoadBalancer